"""empty message

Revision ID: 15782ce5d06f
Revises: 
Create Date: 2021-06-01 21:05:51.132275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15782ce5d06f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tstokbapok', sa.Column('asalpasok_id1', sa.Integer(), nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id2', sa.Integer(), nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id3', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'tstokbapok', type_='foreignkey')
    op.create_foreign_key(None, 'tstokbapok', 'tasalpasok', ['asalpasok_id1'], ['id_asalpasok'])
    op.create_foreign_key(None, 'tstokbapok', 'tasalpasok', ['asalpasok_id3'], ['id_asalpasok'])
    op.create_foreign_key(None, 'tstokbapok', 'tasalpasok', ['asalpasok_id2'], ['id_asalpasok'])
    op.drop_column('tstokbapok', 'asalpasok_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tstokbapok', sa.Column('asalpasok_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'tstokbapok', type_='foreignkey')
    op.drop_constraint(None, 'tstokbapok', type_='foreignkey')
    op.drop_constraint(None, 'tstokbapok', type_='foreignkey')
    op.create_foreign_key(None, 'tstokbapok', 'tasalpasok', ['asalpasok_id'], ['id_asalpasok'])
    op.drop_column('tstokbapok', 'asalpasok_id3')
    op.drop_column('tstokbapok', 'asalpasok_id2')
    op.drop_column('tstokbapok', 'asalpasok_id1')
    # ### end Alembic commands ###
