"""empty message

Revision ID: 184f6521d481
Revises: b506e6f02daa
Create Date: 2021-06-03 14:58:03.475612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184f6521d481'
down_revision = 'b506e6f02daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
