"""empty message

Revision ID: 3dc20ff654e9
Revises: 15782ce5d06f
Create Date: 2021-06-03 13:57:04.633027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc20ff654e9'
down_revision = '15782ce5d06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tstokbapok', sa.Column('asal_pasok', sa.String(length=15), nullable=False))
    op.add_column('tstokbapok', sa.Column('bulan', sa.String(length=15), nullable=False))
    op.add_column('tstokbapok', sa.Column('minggu', sa.String(length=15), nullable=False))
    op.add_column('tstokbapok', sa.Column('tahun', sa.String(length=5), nullable=False))
    op.drop_constraint(None, 'tstokbapok', type_='foreignkey')
    op.drop_column('tstokbapok', 'asalpasok_id1')
    op.drop_column('tstokbapok', 'asalpasok_id')
    op.drop_column('tstokbapok', 'asalpasok_id3')
    op.drop_column('tstokbapok', 'asalpasok_id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tstokbapok', sa.Column('asalpasok_id2', sa.INTEGER(), nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id3', sa.INTEGER(), nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id', sa.INTEGER(), nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id1', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'tstokbapok', 'tasalpasok', ['asalpasok_id'], ['id_asalpasok'])
    op.drop_column('tstokbapok', 'tahun')
    op.drop_column('tstokbapok', 'minggu')
    op.drop_column('tstokbapok', 'bulan')
    op.drop_column('tstokbapok', 'asal_pasok')
    # ### end Alembic commands ###
