"""empty message

Revision ID: 7183a0d860f3
Revises: 184f6521d481
Create Date: 2021-06-06 22:57:06.657912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7183a0d860f3'
down_revision = '184f6521d481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
