"""empty message

Revision ID: b506e6f02daa
Revises: 3dc20ff654e9
Create Date: 2021-06-03 14:20:29.169483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b506e6f02daa'
down_revision = '3dc20ff654e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasalpasok',
    sa.Column('id_asalpasok', sa.Integer(), nullable=False),
    sa.Column('asal_pasok', sa.String(length=20), nullable=False),
    sa.Column('ket', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_asalpasok')
    )
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('tasalpasok')
    # ### end Alembic commands ###
