"""empty message

Revision ID: e9195ec78836
Revises: 7183a0d860f3
Create Date: 2021-06-13 00:25:23.115828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9195ec78836'
down_revision = '7183a0d860f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasalpasok')
    op.add_column('tstokbapok', sa.Column('asal_pasok', sa.String(length=15), nullable=False))
    op.add_column('tstokbapok', sa.Column('bulan', sa.String(length=15), nullable=False))
    op.add_column('tstokbapok', sa.Column('minggu', sa.String(length=15), nullable=False))
    op.add_column('tstokbapok', sa.Column('tahun', sa.String(length=5), nullable=False))
    op.drop_constraint('tstokbapok_ibfk_2', 'tstokbapok', type_='foreignkey')
    op.drop_column('tstokbapok', 'asalpasok_id2')
    op.drop_column('tstokbapok', 'asalpasok_id3')
    op.drop_column('tstokbapok', 'asalpasok_id')
    op.drop_column('tstokbapok', 'asalpasok_id1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tstokbapok', sa.Column('asalpasok_id1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tstokbapok', sa.Column('asalpasok_id2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tstokbapok_ibfk_2', 'tstokbapok', 'tasalpasok', ['asalpasok_id'], ['id_asalpasok'])
    op.drop_column('tstokbapok', 'tahun')
    op.drop_column('tstokbapok', 'minggu')
    op.drop_column('tstokbapok', 'bulan')
    op.drop_column('tstokbapok', 'asal_pasok')
    op.create_table('tasalpasok',
    sa.Column('id_asalpasok', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('asal_pasok', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ket', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_asalpasok'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
